services:
  - type: web
    name: prometric-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: prometric-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: prometric-db
    databaseName: prometric
    user: prometric